name: Update Awattar Data

on:
  schedule:
    - cron: "14 9 * * *"  # täglich 23:05 UTC (~01:05 MEZ)
  workflow_dispatch:       # Manuell auslösbar

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run script
        run: python strompreise.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add strompreise_awattar.csv
          git commit -m "📈 Automatisches Update der Strompreise: $(date +'%Y-%m-%d')" || echo "Nichts zu committen"
          git push
